#language: java
#jdk:
#  - oraclejdk8
#install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - mvn cobertura:cobertura
#script:
#  - mvn test
#
#dist: trusty

language: java
sudo: required
services:
  - docker
before_install:
  - docker build -t hoanganleba146/online-booking .
script:
  - docker run -d -p 8080:8080 hoanganleba146/online-booking
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hoanganleba146/online-booking

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: movie-booking
  env: MovieBooking-env-1
  bucket_name: elasticbeanstalk-ap-southeast-1-792974750178
  on:
    branch:
      - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
